name: place_repository
description: The Repo that handles places
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  city_repository:
    path: ../city_repository
  # equatable: ^2.0.5
  cloud_firestore: ^4.9.2
  # firebase_storage: ^11.6.0
  # rxdart: ^0.27.7
  # path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true